# -*- coding: utf-8 -*-
"""Hand-curated champion metadata that Riot's public data does not expose.

Data Dragon gives us names, classes and skins, but nothing about a champion's
gender, species or home region -- which are exactly the axes an artist wants
to filter a reference session on. This table fills that gap.

If you disagree with a call (some are genuinely debatable -- Jax's species,
Lucian's region), edit it here and re-run `python tools/build_data.py`.

gender:  female | male | other
         ("other" covers dual beings like Kindred and everything with no
         gendered presentation at all -- constructs, void creatures, elementals)
species: see SPECIES_LABELS in build_data.py
region:  see REGION_LABELS in build_data.py
"""

# alias -> (gender, species, region)
CHAMPIONS = {
    "Aatrox":       ("male",   "darkin",    "runeterra"),
    "Ahri":         ("female", "vastaya",   "ionia"),
    "Akali":        ("female", "human",     "ionia"),
    "Akshan":       ("male",   "human",     "shurima"),
    "Alistar":      ("male",   "beast",     "noxus"),
    "Ambessa":      ("female", "human",     "noxus"),
    "Amumu":        ("male",   "undead",    "shurima"),
    "Anivia":       ("female", "god",       "freljord"),
    "Annie":        ("female", "human",     "noxus"),
    "Aphelios":     ("male",   "human",     "targon"),
    "Ashe":         ("female", "human",     "freljord"),
    "AurelionSol":  ("male",   "celestial", "targon"),
    "Aurora":       ("female", "vastaya",   "freljord"),
    "Azir":         ("male",   "ascended",  "shurima"),
    "Bard":         ("male",   "celestial", "runeterra"),
    "Belveth":      ("female", "void",      "void"),
    "Blitzcrank":   ("other",  "construct", "zaun"),
    "Brand":        ("male",   "elemental", "freljord"),
    "Braum":        ("male",   "human",     "freljord"),
    "Briar":        ("female", "undead",    "noxus"),
    "Caitlyn":      ("female", "human",     "piltover"),
    "Camille":      ("female", "human",     "piltover"),
    "Cassiopeia":   ("female", "beast",     "noxus"),
    "Chogath":      ("other",  "void",      "void"),
    "Corki":        ("male",   "yordle",    "bandle-city"),
    "Darius":       ("male",   "human",     "noxus"),
    "Diana":        ("female", "human",     "targon"),
    "DrMundo":      ("male",   "human",     "zaun"),
    "Draven":       ("male",   "human",     "noxus"),
    "Ekko":         ("male",   "human",     "zaun"),
    "Elise":        ("female", "beast",     "shadow-isles"),
    "Evelynn":      ("female", "demon",     "runeterra"),
    "Ezreal":       ("male",   "human",     "piltover"),
    "Fiddlesticks": ("other",  "demon",     "runeterra"),
    "Fiora":        ("female", "human",     "demacia"),
    "Fizz":         ("male",   "vastaya",   "bilgewater"),
    "Galio":        ("male",   "construct", "demacia"),
    "Gangplank":    ("male",   "human",     "bilgewater"),
    "Garen":        ("male",   "human",     "demacia"),
    "Gnar":         ("male",   "yordle",    "freljord"),
    "Gragas":       ("male",   "human",     "freljord"),
    "Graves":       ("male",   "human",     "bilgewater"),
    "Gwen":         ("female", "construct", "shadow-isles"),
    "Hecarim":      ("male",   "undead",    "shadow-isles"),
    "Heimerdinger": ("male",   "yordle",    "piltover"),
    "Hwei":         ("male",   "human",     "ionia"),
    "Illaoi":       ("female", "human",     "bilgewater"),
    "Irelia":       ("female", "human",     "ionia"),
    "Ivern":        ("male",   "spirit",    "ionia"),
    "Janna":        ("female", "elemental", "zaun"),
    "JarvanIV":     ("male",   "human",     "demacia"),
    "Jax":          ("male",   "other",     "shurima"),
    "Jayce":        ("male",   "human",     "piltover"),
    "Jhin":         ("male",   "human",     "ionia"),
    "Jinx":         ("female", "human",     "zaun"),
    "KSante":       ("male",   "human",     "shurima"),
    "Kaisa":        ("female", "human",     "void"),
    "Kalista":      ("female", "undead",    "shadow-isles"),
    "Karma":        ("female", "human",     "ionia"),
    "Karthus":      ("male",   "undead",    "shadow-isles"),
    "Kassadin":     ("male",   "human",     "void"),
    "Katarina":     ("female", "human",     "noxus"),
    "Kayle":        ("female", "celestial", "demacia"),
    "Kayn":         ("male",   "human",     "ionia"),
    "Kennen":       ("male",   "yordle",    "ionia"),
    "Khazix":       ("other",  "void",      "void"),
    "Kindred":      ("other",  "spirit",    "runeterra"),
    "Kled":         ("male",   "yordle",    "noxus"),
    "KogMaw":       ("other",  "void",      "void"),
    "Leblanc":      ("female", "human",     "noxus"),
    "LeeSin":       ("male",   "human",     "ionia"),
    "Leona":        ("female", "human",     "targon"),
    "Lillia":       ("female", "spirit",    "ionia"),
    "Lissandra":    ("female", "human",     "freljord"),
    "Locke":        ("male",   "human",     "demacia"),
    "Lucian":       ("male",   "human",     "shadow-isles"),
    "Lulu":         ("female", "yordle",    "bandle-city"),
    "Lux":          ("female", "human",     "demacia"),
    "Malphite":     ("other",  "elemental", "ixtal"),
    "Malzahar":     ("male",   "human",     "void"),
    "Maokai":       ("male",   "spirit",    "shadow-isles"),
    "MasterYi":     ("male",   "human",     "ionia"),
    "Mel":          ("female", "human",     "noxus"),
    "Milio":        ("male",   "human",     "ixtal"),
    "MissFortune":  ("female", "human",     "bilgewater"),
    "MonkeyKing":   ("male",   "vastaya",   "ionia"),
    "Mordekaiser":  ("male",   "undead",    "noxus"),
    "Morgana":      ("female", "celestial", "demacia"),
    "Naafiri":      ("female", "darkin",    "shurima"),
    "Nami":         ("female", "vastaya",   "bilgewater"),
    "Nasus":        ("male",   "ascended",  "shurima"),
    "Nautilus":     ("male",   "undead",    "bilgewater"),
    "Neeko":        ("female", "vastaya",   "ixtal"),
    "Nidalee":      ("female", "human",     "ixtal"),
    "Nilah":        ("female", "human",     "bilgewater"),
    "Nocturne":     ("other",  "demon",     "runeterra"),
    "Nunu":         ("male",   "human",     "freljord"),
    "Olaf":         ("male",   "human",     "freljord"),
    "Orianna":      ("female", "construct", "piltover"),
    "Ornn":         ("male",   "god",       "freljord"),
    "Pantheon":     ("male",   "celestial", "targon"),
    "Poppy":        ("female", "yordle",    "demacia"),
    "Pyke":         ("male",   "undead",    "bilgewater"),
    "Qiyana":       ("female", "human",     "ixtal"),
    "Quinn":        ("female", "human",     "demacia"),
    "Rakan":        ("male",   "vastaya",   "ionia"),
    "Rammus":       ("other",  "beast",     "shurima"),
    "RekSai":       ("female", "void",      "void"),
    "Rell":         ("female", "human",     "noxus"),
    "Renata":       ("female", "human",     "zaun"),
    "Renekton":     ("male",   "ascended",  "shurima"),
    "Rengar":       ("male",   "vastaya",   "ixtal"),
    "Riven":        ("female", "human",     "noxus"),
    "Rumble":       ("male",   "yordle",    "bandle-city"),
    "Ryze":         ("male",   "human",     "runeterra"),
    "Samira":       ("female", "human",     "noxus"),
    "Sejuani":      ("female", "human",     "freljord"),
    "Senna":        ("female", "human",     "shadow-isles"),
    "Seraphine":    ("female", "human",     "piltover"),
    "Sett":         ("male",   "vastaya",   "ionia"),
    "Shaco":        ("male",   "demon",     "runeterra"),
    "Shen":         ("male",   "human",     "ionia"),
    "Shyvana":      ("female", "dragon",    "demacia"),
    "Singed":       ("male",   "human",     "zaun"),
    "Sion":         ("male",   "undead",    "noxus"),
    "Sivir":        ("female", "human",     "shurima"),
    "Skarner":      ("male",   "beast",     "shurima"),
    "Smolder":      ("male",   "dragon",    "camavor"),
    "Sona":         ("female", "human",     "demacia"),
    "Soraka":       ("female", "celestial", "targon"),
    "Swain":        ("male",   "human",     "noxus"),
    "Sylas":        ("male",   "human",     "demacia"),
    "Syndra":       ("female", "human",     "ionia"),
    "TahmKench":    ("male",   "demon",     "runeterra"),
    "Taliyah":      ("female", "human",     "shurima"),
    "Talon":        ("male",   "human",     "noxus"),
    "Taric":        ("male",   "celestial", "targon"),
    "Teemo":        ("male",   "yordle",    "bandle-city"),
    "Thresh":       ("male",   "undead",    "shadow-isles"),
    "Tristana":     ("female", "yordle",    "bandle-city"),
    "Trundle":      ("male",   "beast",     "freljord"),
    "Tryndamere":   ("male",   "human",     "freljord"),
    "TwistedFate":  ("male",   "human",     "bilgewater"),
    "Twitch":       ("male",   "beast",     "zaun"),
    "Udyr":         ("male",   "human",     "freljord"),
    "Urgot":        ("male",   "human",     "zaun"),
    "Varus":        ("male",   "darkin",    "ionia"),
    "Vayne":        ("female", "human",     "demacia"),
    "Veigar":       ("male",   "yordle",    "bandle-city"),
    "Velkoz":       ("other",  "void",      "void"),
    "Vex":          ("female", "yordle",    "shadow-isles"),
    "Vi":           ("female", "human",     "piltover"),
    "Viego":        ("male",   "undead",    "camavor"),
    "Viktor":       ("male",   "human",     "zaun"),
    "Vladimir":     ("male",   "human",     "noxus"),
    "Volibear":     ("male",   "god",       "freljord"),
    "Warwick":      ("male",   "beast",     "zaun"),
    "Xayah":        ("female", "vastaya",   "ionia"),
    "Xerath":       ("male",   "ascended",  "shurima"),
    "XinZhao":      ("male",   "human",     "demacia"),
    "Yasuo":        ("male",   "human",     "ionia"),
    "Yone":         ("male",   "spirit",    "ionia"),
    "Yorick":       ("male",   "human",     "shadow-isles"),
    "Yunara":       ("female", "human",     "ionia"),
    "Yuumi":        ("female", "beast",     "bandle-city"),
    "Zaahen":       ("male",   "darkin",    "runeterra"),
    "Zac":          ("other",  "construct", "zaun"),
    "Zed":          ("male",   "human",     "ionia"),
    "Zeri":         ("female", "human",     "zaun"),
    "Ziggs":        ("male",   "yordle",    "bandle-city"),
    "Zilean":       ("male",   "human",     "shurima"),
    "Zoe":          ("female", "celestial", "targon"),
    "Zyra":         ("female", "plant",     "ixtal"),
}
